Garnettanner/vm setup
StudentOrganisationForAerospaceResearch/DevelopmentResources pull request #6
Opened 2018-01-14 23:35 UTC by Gtanner00

I've made changes based on Enoch's recommendations. 
The guide now only concerns setting up the virtual machine.  I've also moved it into the general Documentation directory.

Enoch, do you plan to push your changes to the install.sh?
I can improve the guide on how to set up the build environment.

2018-01-15 23:19 UTC, ExtraGravity requested changes

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +== 1. Install Virtualbox
Pretty odd to have the numbering here. I dont' think the numbers are necessary.

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +This guide assumes the host operating system is 64 bit Windows
Missing period.

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +Download https://www.virtualbox.org/wiki/Downloads[Oracle Virtual Box]
Missing period.

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +The latest version at writting was 5.2.4.
Writting -> writing

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +Create a new virtual machine in Virtualbox using the _New_ icon.
Headers should have an empty line above and below them.

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +image::https://github.com/StudentOrganisationForAerospaceResearch/DevelopmentResources/blob/garnettanner/stm32-example/STM32Resources/BuildEnvironment_Setup/images/1.PNG[]
These links are very likely to break, you should use relative paths.

You can reference the README from this project.
https://raw.githubusercontent.com/JeLLyNinjas/TerminalFighter/master/README.adoc
https://github.com/JeLLyNinjas/TerminalFighter/blob/master/README.adoc

Usually, if your name appears anywhere in a file, it's a red flag :)

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +Mint reccomends 20 GB of hard disk and 1 GB of RAM for a bare minimal installation. Give yourself extra RAM and space for project files and application packages.
One sentence per line

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +Use the default options if unsure
I would reword to

`The defaulting are usually fine.`

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +Select the default options if unsure of anything.
I don't think this line is necessary, this was stated before.

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +==== Extra Tip
I would rename this to `Shared Folder between the Host and VM (Optional)`

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +Check _Automount_ and _Make Perminant_ After you mount the drive you need to run
_Make Perminant_ should be _Make Permanent_ right?

2018-01-15 23:19 UTC, enochtsang commented on Documentation/LinuxVMGuide/README.adoc
> +the following command to give Linux permissions to access the files.
This should stick with the previous line, one sentence one line.

2018-02-27 07:03 UTC, enochtsang commented
Don't think garnet is gonna get around to this, which is fine.

2018-02-27 07:03 UTC, closed without merging

2018-02-27 17:30 UTC, Gtanner00 commented
Sorry this was left unfinished. My time was better served getting hardware ready.